package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// DiaryTag represents a row from 'deairy.diary_tags'.
type DiaryTag struct {
	ID        string    `json:"id"`         // id
	DiaryID   string    `json:"diary_id"`   // diary_id
	Name      string    `json:"name"`       // name
	CreatedAt time.Time `json:"created_at"` // created_at
}
