package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// User represents a row from 'deairy.users'.
type User struct {
	ID        string    `json:"id"`         // id
	Name      string    `json:"name"`       // name
	Email     string    `json:"email"`      // email
	CreatedAt time.Time `json:"created_at"` // created_at
	UpdatedAt time.Time `json:"updated_at"` // updated_at
}
